version: "3"

services:
  api-server:
    image: node:current-alpine3.18
    container_name: revox-api
    working_dir: /app/api
    volumes:
      - ./app/api:/app/api
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm start"]

  db-server:
    image: postgres:16.0
    container_name: revox-db
    volumes:
      - ./app/db:/var/lib/postgresql/data
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      PGUSER: revox
      POSTGRES_PASSWORD: changepassword
    restart: unless-stopped
    ports:
      - 5432:5432
